import { ClerkProvider } from "@clerk/nextjs";
import Link from "next/link";
import { UserButton } from "@clerk/nextjs";
import "./globals.css";
import { Inter } from "next/font/google";
import NavigationMenuDemo from "../components/NavMenu";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { auth } from "@clerk/nextjs";
import { db } from "@/db";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { userId } = auth();
  const queryText = `
  SELECT *
  FROM users_hosts
  WHERE clecks_user_id = $1
`;
  const hostResult = await db.query(queryText, [userId]);
  console.log("host", hostResult.rows[0].id);
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <>
            <Header />

            <NavigationMenuDemo host={hostResult.rows[0].id} />
            <div id="wrapper">{children}</div>
          </>
          <nav>
            {/* <Link href="/">Home</Link>
        <Link href="/pages/posts">Postings</Link>
        <Link href="/pages/hosts">Hosts</Link> */}
          </nav>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
