import { ClerkProvider } from '@clerk/nextjs'
import Link from "next/link"
import { UserButton } from "@clerk/nextjs";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
    <nav>
        <Link href="/">Home</Link>
        <Link href="/pages/posts">Postings</Link>
        <Link href="/pages/hosts">Hosts</Link>
        <UserButton afterSignOutUrl='/'/>
    </nav>
      <body className={inter.className}>{children}</body>
    </html>
    </ClerkProvider>
  );
}
